spring:
  application:
    name: house_raspberry

app:
  communication:
    type: rest #rest ou grpc
  led:
    url: ${APP_LED_URL:http://localhost:8090}

grpc:
  client:
    ledServer:
      address: 'static://${GRPC_LED_HOST:localhost}:9090'
      negotiationType: plaintext